### ISSUE TITLE
Scratch image is not showing. 

### ISSUE THREAD

**Issue by dagulri** [vintage/scratcher#12]
I cloned it. everything are good working. 
But Scratch image is not showing. 
other asset image is good working but only Scratch image is not showing.

I did packages get and upgrade. 
and try change other file. But Scratch image can not change.
(other image is good to change. ex. google.png)
and It same with other emulator. 

image: Image.asset('assets/scratch.png'),
<img width="331" alt="Screen Shot 2020-07-25 at 9 39 45 AM" src="https://user-images.githubusercontent.com/50366559/88444980-d25e5f00-ce5a-11ea-9e87-155a56843ad0.png">

Also, Give me some advise for apply network image.
Thanks.

**Comment by vintage** [comment]
Mind to share output of `flutter doctor` command?

**Comment by dagulri** [comment]
> Mind to share output of `flutter doctor` command?

here is flutter doctor command. 

![Screen Shot 2020-07-26 at 5 27 15 AM](https://user-images.githubusercontent.com/50366559/88465811-efe60400-cf00-11ea-826e-591444c89c48.png)

**Comment by vintage** [comment]
The plugin itself is only tested against `stable` branch of Flutter, which means newest supported version is `1.17.5`. Let me know if the issue still occurs on stable channel.

**Comment by dagulri** [comment]
> The plugin itself is only tested against `stable` branch of Flutter, which means newest supported version is `1.17.5`. Let me know if the issue still occurs on stable channel.

Yes, It's work! Thanks.
