### ISSUE TITLE
image attribute doesn't work 

### ISSUE THREAD

**Issue by dariobrux** [vintage/scratcher#13]
Hi,

I'm using the 1.3.0 version of this library, but the attribute **image** doesn't work.

Thanks,

Dario

**Comment by vintage** [comment]
What version of Flutter are use using? The plugin itself supports officially only stable channel. See related issues:

- https://github.com/vintage/scratcher/issues/11
- https://github.com/vintage/scratcher/issues/12

**Comment by dariobrux** [comment]
Hi @vintage ,

thanks for your answer. 
This is great! after changing the flutter branch, the plugin has worked correctly.

Final `flutter doctor` configuration is:
![image](https://user-images.githubusercontent.com/22790670/89334065-41775700-d696-11ea-8548-ea9f185a3457.png)

Thanks.
