### ISSUE TITLE
BrushSize dinamically changing

### ISSUE THREAD

**Issue by dariobrux** [vintage/scratcher#14]
Hi,

I have this situation in the same screen:
- the Scratcher widget with a network image that covers its Container widget child;
- a SeekBar widget that's used to change dynamically the `brushSize` value of the Scratcher above.

When I change the brushSize value through the SeekBar, I noticed that all the already scratched portion changes its brush. Instead, I'd like to get only the next scratch with the new brushSize value.

So, is there a way to prevent this situation?

(I'm sorry but I'm new with Flutter, maybe this has already been done).

Thank you very much,

Dario

**Comment by vintage** [comment]
Hey @dariobrux,

Indeed, there's been a bug how the dynamic brush size is handled. It should work properly in the 1.4.0 release https://pub.dev/packages/scratcher Let me know :)

**Comment by dariobrux** [comment]
Hi @vintage.

Thank you very much, I've tried with 1.4.0 and it works perfectly!! This is very great.
Happy to use this library!

Dario
