### ISSUE TITLE
It is lagging

### ISSUE THREAD

**Issue by appnish** [vintage/scratcher#19]
It is very nice and the same what I was looking for. But it is lagging much when we scratch. It is not smooth. I tried on several devices having good RAM

**Comment by vintage** [comment]
@appnish 

1. `flutter doctor`
2. What version of scratcher are you using?
3. Does the problem persist on provided example app https://github.com/vintage/scratcher/tree/master/example ?
4. What exact devices were you running the tests? On OnePlus 6T I didn't encounter perf issues.
