### ISSUE TITLE
OnPanStart, Update and End Gestures callbacks

### ISSUE THREAD

**Issue by nooralibutt** [vintage/scratcher#21]
I need these callbacks outside so that I can implement sound effects while user scratches.

**Comment by vintage** [comment]
Sounds like a reasonable use case to cover. Will expose additional callbacks later this week.

**Comment by vintage** [comment]
@nooralibutt done. `onScratchStart`, `onScratchUpdate` and `onScratchEnd` landed in `1.4.1` https://pub.dev/packages/scratcher ;)

**Comment by nooralibutt** [comment]
@vintage wow, amazing. Job well done.

Although, I don't need it but I think you should have passed the details argument with these callbacks, that was comping with pan gesture. Thanks though.

**Comment by vintage** [comment]
Nah, I don't see any real use-case for these. Will add meaningful data to the callbacks when proper issue got reported.

**Comment by nooralibutt** [comment]
Awesome.
