### ISSUE TITLE
Wrong size when using CachedNetworkImage

### ISSUE THREAD

**Issue by rubenaster** [vintage/scratcher#32]
Hey,

I'm using Scratcher with CachedNetworkImage and the issue I have is that on the first call of OnDraw after the image is loaded I get a size of (10, 10). Quickly afterwards OnDraw is called again with the correct size.

The problem is that the first call of OnDraw already initializes the points lists.

Now my current workaround is to check in OnDraw if the size has changed and if so I re-initialize the points. Of course this might lead to issues.

It works for now since the OnDraw calls appear quickly one ofter the other but maybe you have a better idea?

**Comment by vintage** [comment]
Potential solution to this would be recalculating the scratcher progress when the size of canvas changes. Probably somewhere here https://github.com/vintage/scratcher/blob/master/lib/widgets.dart#L140 a test against constraints could be added to solve the problem.

Well, it would also solve the https://github.com/vintage/scratcher/issues/30 as that's the same thing.

**Comment by vintage** [comment]
Fixed in `2.1.0` https://pub.dev/packages/scratcher
