### ISSUE TITLE
Support Scratcher for web using HTML renderer 

### ISSUE THREAD

**Issue by ineelp** [vintage/scratcher#33]
Hi @vintage,

Currently, the `scratcher` plugin works well using `canvaskit` for the web platform. But the problem is that it freezes up the app when the app hits a **performance issue** and it **forces the browser to reload** on **`iOS`** devices.  This is producible on both `2.0.0` and `2.2.0` flutter stable channel. When using `html` renderer, it only displays the image and it can't be scratch off.  

Are there any workarounds or suggestions to get this plugin working using `html` renderer?

Thanks,

Neel

**Comment by souvik-bera** [comment]
Same issue. looking for some updates

**Comment by vintage** [comment]
As the `Paint` implementation is not supported on web renderer, there is not much I can do here. The performance has been improved through https://github.com/vintage/scratcher/pull/37 If anyone got other approaches to squeeze it even more - feel free to submit PR!
