### ISSUE TITLE
Spiky drawing

### ISSUE THREAD

**Issue by m-mak** [vintage/scratcher#39]
When drawing the circular paint changes to **spiky drawings**, see screencast below.

Reproduce:
- [Scratcher 2.2.0 Example Project](https://github.com/vintage/scratcher/tree/master/example)
- Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
- Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_x64"
 
(Also tested with Flutter 2.10.5, same bug.)

Tested on iPhone 13, Samsung S21 and Simulators. Same result everywhere. 

https://user-images.githubusercontent.com/13810971/168308646-c36b7a81-5adc-48d8-9fbd-998ff9a71d70.mov

**Comment by mak-online** [comment]
https://github.com/vintage/scratcher/pull/43 solves the issue!

**Comment by vintage** [comment]
The fix has been released in 2.3.0 - https://pub.dev/packages/scratcher
