### ISSUE TITLE
Update for flutter 3.0 is needed

### ISSUE THREAD

**Issue by Srini-B** [vintage/scratcher#41]
below is the issue when running the app in flutter 3.0+

`/opt/homebrew/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/scratcher-2.2.0/lib/widgets.dart:180:44: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/opt/homebrew/Caskroom/flutter/2.8.1/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
                            WidgetsBinding.instance?.addPostFrameCallback((_) {`

**Comment by vintage** [comment]
Fixed by @andersonmendess https://github.com/vintage/scratcher/pull/40
