### ISSUE TITLE
Can tracks appear automatically?

### ISSUE THREAD

**Issue by lizhuoyuan** [vintage/scratcher#57]
I hope that I can call a method, and then the track will automatically appear (simulating finger sliding), and then all will be displayed

**Comment by vintage** [comment]
Duplicate of https://github.com/vintage/scratcher/issues/45

**Comment by programmerElephant** [comment]
> 我希望可以调用一个方法，然后轨道会自动出现（模拟手指滑动），然后全部显示出来

did you solved it ?
