### ISSUE TITLE
ON WEB ITS NOT WORKING

### ISSUE THREAD

**Issue by rajvaya** [vintage/scratcher#8]
i tried it on web when i click on card it becomes white and when i scratch it 100% it revels check the issue and fix this plugin is power full

**Comment by chkkassd** [comment]
I have the same problem, it doesn't work on flutter web

**Comment by vintage** [comment]
Correct, the plugin doesn't support the web platform yet. That's not a priority for now, as web is still in beta version.

**Comment by clocksmith** [comment]
Is there any reason why it wouldn't work on web?

**Comment by vintage** [comment]
@clocksmith I'm gonna look into this one after incoming Flutter release (next week), as web becomes more and more stable. There is a chance it would work out of the box.

**Comment by rajvaya** [comment]
@vintage any updates on package it is working on web or not ?

**Comment by vintage** [comment]
Tried on beta channel, doesn't yet work as expected.

**Comment by ismadev** [comment]
@vintage any idea when is it working? it depends on you or on the web channel?

**Comment by vintage** [comment]
@ismadev I haven't investigated it due to lack of spare time at the moment. PRs are more than welcome.

**Comment by vintage** [comment]
Version `1.5.0` supports WEB platform https://pub.dev/packages/scratcher 🥳
