### ISSUE TITLE
use image: Image.asset() still show black scratcher

### ISSUE THREAD

**Issue by ben060788** [vintage/scratcher#9]
`version 1.3.0`
i want to use a image to cover child widget 
this is my scratcher
```
Container(
          width: 200,
          height: 200,
          child: Scratcher(
            key: key,
            brushSize: 30,
            threshold: 50,
            image: Image.asset(
              'assets/scratcher01.jpg',
              fit: BoxFit.cover,
            ),
            onChange: (value) {},
            child: Container(
              height: double.infinity,
              width: double.infinity,
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                      'Scratch the screen to win',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 24, color: Colors.amber),
                    ),
                  ],
                ),
              ),
              color: Colors.grey,
            ),
          ),
        ),
```

Scratcher widget
```
Scratcher({
    Key key,
    @required this.child,
    this.threshold,
    this.brushSize = 25,
    this.accuracy = ScratchAccuracy.high,
    this.color = Colors.black,
    this.image,
    this.onChange,
    this.onThreshold,
  }) : super(key: key);
```
the default black color may cause the scratcher show black
so it can't be covered by the image 
Please check, thank you.

**Comment by vintage** [comment]
Any logs in the console? Maybe the asset couldn't be located in the app? You could try with the network image like `Image.network("https://p.bigstockphoto.com/GeFvQkBbSLaMdpKXF1Zv_bigstock-Aerial-View-Of-Blue-Lakes-And--227291596.jpg")` to see if behaves differently. As I said - the examples in the repo are also using the image-as-scratch-area and it seems to work fine there.

**Comment by ben060788** [comment]
no error log in the console.

i try the example with image.network in scratch_box widget
```
return Container(
      width: 80,
      height: 80,
      margin: const EdgeInsets.all(10),
      child: Scratcher(
        accuracy: ScratchAccuracy.low,
//         color: Colors.red,
        image: Image.network('https://p.bigstockphoto.com/GeFvQkBbSLaMdpKXF1Zv_bigstock-Aerial-View-Of-Blue-Lakes-And--227291596.jpg'),
        brushSize: 15,
        threshold: 60,
        onThreshold: () {
          setState(() {
            opacity = 1;
            isScratched = true;
          });
          widget.onScratch?.call();
        },
        child: Container(
          child: widget.animation == null
              ? icon
              : ScaleTransition(
                  scale: widget.animation,
                  child: icon,
                ),
        ),
      ),
    );
```
and the result on my simulator
<img width="387" alt="螢幕快照 2020-01-16 10 52 13" src="https://user-images.githubusercontent.com/18287647/72490630-beee8d80-3852-11ea-9793-808a1f990ff7.png">

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale zh-Hant-TW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by vintage** [comment]
Weird, works for me locally. The only difference which I can point out for now is the version of Flutter - `1.9.1 vs 1.12.13`, but it shouldn't be the case here. The lib itself worked with previous version of Flutter as well. Could you check on real device and on iOS to see if the problem is not strictly related to this particular emulator?

**Comment by ben060788** [comment]
I try to build on my real device
1. ASUS zenfone 3 android 8.0 
2. iphone 6 iOS 12.4.4
3. iPad mini 5th iPadOS 13.3

all of them occur this problem

The good news is the problem was solved because i upgrade my flutter SDK version to `1.12.13+hotfix.7`

Thanks for your help. ^_^

**Comment by vintage** [comment]
Glad to hear it's solved. I've set Flutter version to 1.12+ as minimum project requirement in pubspec.yaml, thanks for your help!
